from typing import TYPE_CHECKING

from athena_kit._import_utils import import_attr

if TYPE_CHECKING:
    from athena_kit.core.models import BaseAthenaModel, LabelIntEnum, LabelStrEnum
    from athena_kit.core.tabular import (
        BaseTableRow,
        SourceField,
        TableBackend,
        TableField,
        TableLocator,
        TableRepository,
        dataframe_to_models,
        deserialize_cell_value,
        models_to_dataframe,
        serialize_cell_value,
        table_rows_to_dataframe,
    )
    from athena_kit.core.temporal import (
        DateBoundaryPolicy,
        DateOutputFormat,
        DateTimeOutputFormat,
        NaiveDateTimePolicy,
        TimeOutputFormat,
        TimestampUnit,
        coerce_timezone,
        get_default_timezone,
        get_timezone,
        is_aware_datetime,
        is_naive_datetime,
        normalize_datetime_timezone,
        reload_default_timezone,
        resolve_date_boundary,
        set_default_timezone,
        timezone_context,
    )
    from athena_kit.core.temporal.codec import (
        DateCodec,
        DateCodecOptions,
        DateInput,
        DateOutput,
        DateTimeCodec,
        DateTimeCodecOptions,
        DateTimeInput,
        DateTimeOutput,
        TemporalCodec,
        TemporalCodecOptions,
        TimeCodec,
        TimeCodecOptions,
        TimeInput,
        TimeOutput,
        format_date,
        format_datetime,
        format_time,
        parse_date,
        parse_datetime,
        parse_time,
    )
    from athena_kit.core.values import (
        first_non_empty,
        first_not_none,
        first_truthy,
        optional_map,
        optional_map_or,
        optional_map_or_else,
        optional_or,
        optional_or_else,
        safe_getattr,
    )

__all__ = (
    "BaseAthenaModel",
    "LabelIntEnum",
    "LabelStrEnum",
    "TableLocator",
    "TableBackend",
    "serialize_cell_value",
    "deserialize_cell_value",
    "TableField",
    "SourceField",
    "BaseTableRow",
    "TableRepository",
    "dataframe_to_models",
    "models_to_dataframe",
    "table_rows_to_dataframe",
    "TemporalCodec",
    "DateCodec",
    "DateCodecOptions",
    "DateInput",
    "DateOutput",
    "DateTimeCodec",
    "DateTimeCodecOptions",
    "DateTimeInput",
    "DateTimeOutput",
    "TemporalCodecOptions",
    "TimeCodec",
    "TimeCodecOptions",
    "TimeInput",
    "TimeOutput",
    "format_date",
    "format_datetime",
    "format_time",
    "parse_date",
    "parse_datetime",
    "parse_time",
    "normalize_datetime_timezone",
    "resolve_date_boundary",
    "is_aware_datetime",
    "is_naive_datetime",
    "coerce_timezone",
    "get_default_timezone",
    "get_timezone",
    "reload_default_timezone",
    "set_default_timezone",
    "timezone_context",
    "DateBoundaryPolicy",
    "DateOutputFormat",
    "DateTimeOutputFormat",
    "NaiveDateTimePolicy",
    "TimeOutputFormat",
    "TimestampUnit",
    "first_non_empty",
    "first_not_none",
    "first_truthy",
    "optional_map",
    "optional_map_or",
    "optional_map_or_else",
    "optional_or",
    "optional_or_else",
    "safe_getattr",
)

_dynamic_imports = {
    "BaseAthenaModel": "models",
    "LabelIntEnum": "models",
    "LabelStrEnum": "models",
    "TableLocator": "tabular",
    "TableBackend": "tabular",
    "serialize_cell_value": "tabular",
    "deserialize_cell_value": "tabular",
    "TableField": "tabular",
    "SourceField": "tabular",
    "BaseTableRow": "tabular",
    "TableRepository": "tabular",
    "dataframe_to_models": "tabular",
    "models_to_dataframe": "tabular",
    "table_rows_to_dataframe": "tabular",
    "TemporalCodec": "temporal.codec",
    "DateCodec": "temporal.codec",
    "DateCodecOptions": "temporal.codec",
    "DateInput": "temporal.codec",
    "DateOutput": "temporal.codec",
    "DateTimeCodec": "temporal.codec",
    "DateTimeCodecOptions": "temporal.codec",
    "DateTimeInput": "temporal.codec",
    "DateTimeOutput": "temporal.codec",
    "TemporalCodecOptions": "temporal.codec",
    "TimeCodec": "temporal.codec",
    "TimeCodecOptions": "temporal.codec",
    "TimeInput": "temporal.codec",
    "TimeOutput": "temporal.codec",
    "format_date": "temporal.codec",
    "format_datetime": "temporal.codec",
    "format_time": "temporal.codec",
    "parse_date": "temporal.codec",
    "parse_datetime": "temporal.codec",
    "parse_time": "temporal.codec",
    "normalize_datetime_timezone": "temporal",
    "resolve_date_boundary": "temporal",
    "is_aware_datetime": "temporal",
    "is_naive_datetime": "temporal",
    "coerce_timezone": "temporal",
    "get_default_timezone": "temporal",
    "get_timezone": "temporal",
    "reload_default_timezone": "temporal",
    "set_default_timezone": "temporal",
    "timezone_context": "temporal",
    "DateBoundaryPolicy": "temporal",
    "DateOutputFormat": "temporal",
    "DateTimeOutputFormat": "temporal",
    "NaiveDateTimePolicy": "temporal",
    "TimeOutputFormat": "temporal",
    "TimestampUnit": "temporal",
    "first_non_empty": "values",
    "first_not_none": "values",
    "first_truthy": "values",
    "optional_map": "values",
    "optional_map_or": "values",
    "optional_map_or_else": "values",
    "optional_or": "values",
    "optional_or_else": "values",
    "safe_getattr": "values",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    result = import_attr(attr_name, module_name, __spec__.parent)
    globals()[attr_name] = result
    return result


def __dir__() -> list[str]:
    return list(__all__)
